apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../after
  - ../pre-processing
  - envoy-filter.yaml
  - plugins-configmap.yaml

images:
  - name: praxis-extproc
    newName: quay.io/maas/praxis-extproc
    newTag: llmisvc-model-provider-resolver
