# Keep in sync with deployment/base/maas-controller/default/maas-tenant-parameters.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: maas-tenant-parameters
  labels:
    app.kubernetes.io/part-of: models-as-a-service
data:
  gateway-namespace: openshift-ingress
  gateway-name: maas-default-gateway
  app-namespace: opendatahub
  cluster-audience: https://kubernetes.default.svc
  api-key-max-expiration-days: "90"
