apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: maas-api-auth-policy
  namespace: opendatahub
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: maas-api-route
  rules:
    authentication:
      openshift-identities:
        kubernetesTokenReview:
          audiences:
            - openshift
        defaults:
          userid:
            expression: auth.identity.user.username
        cache:
          key:
            selector: context.request.http.headers.authorization.@case:lower
          ttl: 600
    response:
      success:
        headers:
          X-MaaS-Username:
            plain:
              selector: auth.identity.user.username
